# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brains, Artificial Brains, and how to deal with them.
email: dirk.guetlin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This text will appear at the bottom of the page. Not sure what to do with it yet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://digyt.github.io/" # the base hostname & protocol for your site
twitter_username: dirkguetlin
github_username:  DiGyt

# Build settings
markdown: kramdown
